---
title: "20181109a Relative Strength Index"
author: "cheungngo"
date: "9 November 2018"
output: word_document
---

### Scraping the data

```{r,message=FALSE}
library(rvest)
library(tidyverse)
```

```{r}
url = 'https://coinmarketcap.com/currencies/bitcoin/historical-data/?start=20171109&end=20181109'
```

```{r}
# function to calculate close
get_close = function(url) {
  html = read_html(url)
  close = html_nodes(html, 'td:nth-child(5)') %>%
    html_text() 
  close = gsub(',','',close)
  options(digits = 9)
  close = as.numeric(close)
  return(close)
}
```

```{r}
# getting the 'close' price
price_close = get_close(url)
head(price_close)
class(price_close)
```


### Calculating the RSI

```{r}
diff = ''; i = 0
for (i in 1:(length(price_close)-1)) {
  diff[i] = price_close[i] - price_close[i+1]
}
diff = as.numeric(diff)
diff_i = ''; RSI = ''
for (i in 1:(length(price_close)-14)) {
  diff_i = diff[i:(i+13)]
  RSI[i] = 100 - 100 / (1 + mean(diff_i[which(diff_i>=0)]) / abs(mean(diff_i[which(diff_i<0)])))
}

```

#### Or to create a function 

```{r}
get_RSI = function(price_close, d) {
  diff = ''; i = 0
  for (i in 1:(length(price_close)-1)) {
    diff[i] = price_close[i] - price_close[i+1]
  }
  diff = as.numeric(diff)
  diff_i = ''; RSI = ''
  for (i in 1:(length(price_close)-d)) {
    diff_i = diff[i:(i+d)]
    RSI[i] = 100 - 100 / (1 + mean(diff_i[which(diff_i>=0)]) /   mean(abs(diff_i[which(diff_i<0)])))
    RSI[i] = as.numeric(RSI[i])
  }
  return(RSI)
}
```

```{r}
RSI = get_RSI(price_close, 14)
RSI = sapply(RSI,as.numeric)
RSI = as.vector(RSI)
class(RSI)
```


### Creating an array of dates

```{r}
# function to get the first and last date
get_date = function(url) {
  html = read_html(url)
  latest = html_nodes(html, '.text-right:nth-child(1) .text-left') %>%
    html_text()
  earliest = html_nodes(html, '.text-right:nth-child(365) .text-left') %>%
    html_text()
  return(c(latest, earliest))
}
```

```{r}
get_date(url)
```

```{r}
latest = as.Date('2018-11-08')
earlist = as.Date('2017-11-08') # note that this would be deferred by one day
dates = seq.Date(from = earlist, to = latest, by = 'day')
head(dates)
```


### Combining the data

```{r}
RSI_r = rev(RSI)
length(dates) - length(RSI)
date_trim = dates[-(1:15)]
index = 1:length(RSI)
length(price_close) - length(RSI)
price_close_r = rev(price_close)
price_trim = price_close_r[-(1:14)]
final = data.frame(Index = index,
                   Date = date_trim,
                   Price = price_trim,
                   RSI = RSI_r)
head(final)
```


### Plotting

```{r}
par(mfrow = c(2,1))
plot(final$Price~final$Date,
     type ='l',
     ylab = 'Price',
     xlab = 'Time')
plot(final$RSI~final$Date,
     type = 'l',
     col = 'red',
     ylab = 'RSI',
     xlab = 'Time')
```


### Further analysis of the RSI

The plotting is not important in our analysis as tradingview or other apps are able to do it much better.

```{r}
# Setting the time frame
ind_1 = length(final$Index)
ind_28 = ind_1 - 27
ind_56 = ind_1 - 55
ind_84 = ind_1 - 83
```

```{r}
# Subsetting the data
final_28 = final[ind_28:ind_1,]
final_56 = final[ind_56:ind_1,]
final_84 = final[ind_84:ind_1,]
```

```{r}
# Linear regression
lm_28 = lm(final_28$RSI~final_28$Index)
lm_56 = lm(final_56$RSI~final_56$Index)
lm_84 = lm(final_84$RSI~final_84$Index)
coef(lm_28)[2]
coef(lm_56)[2]
coef(lm_84)[2]
```

```{r}
# Note that the coef * 28 will be equal to the change in RSI in month
coef(lm_28)[2] * 28
```


#### Or we can do a program for it

```{r}
# Note that the dataframe 'final' should contain columns of 'RSI' and 'Index'
get_RSI_coef = function(final, day) {
  ind_1 = length(final$Index)
  ind_day = ind_1 - day + 1
  final_day = final[ind_day:ind_1,]
  lm_day = lm(final_day$RSI~final_day$Index)
  return(coef(lm_day)[2])
}
```

```{r}
get_RSI_coef(final, 28)
get_RSI_coef(final, 56)
get_RSI_coef(final, 84)
```

